version: 2.1

orbs:
  dwave: dwave/orb-examples@dev:dev

workflows:
  version: 2.1
  tests:
    jobs:
      - dwave/test-osx
      - dwave/test-win
      - dwave/test-linux
      - dwave/test-linux-single-python:
          python-version: "3.7.5"
      - dwave/test-win-single-python:
          python-version: "3.8.6"
      - dwave/test-osx-single-python:
          python-version: "3.9.0"
